using TestMaker.Data.Services.ServiceModels;

namespace TestMaker.Data.Services;

public static class LanguageService
{
    public static List<Language> GetAllCountries()
    {
        return
        [
            new Language { Code = "af", Name = "Afrikaans" },
            new Language { Code = "sq", Name = "Albanian" },
            new Language { Code = "am", Name = "Amharic" },
            new Language { Code = "ar", Name = "Arabic" },
            new Language { Code = "hy", Name = "Armenian" },
            new Language { Code = "az", Name = "Azerbaijani" },
            new Language { Code = "eu", Name = "Basque" },
            new Language { Code = "be", Name = "Belarusian" },
            new Language { Code = "bn", Name = "Bengali" },
            new Language { Code = "bs", Name = "Bosnian" },
            new Language { Code = "bg", Name = "Bulgarian" },
            new Language { Code = "my", Name = "Burmese" },
            new Language { Code = "ca", Name = "Catalan" },
            new Language { Code = "zh", Name = "Chinese" },
            new Language { Code = "hr", Name = "Croatian" },
            new Language { Code = "cs", Name = "Czech" },
            new Language { Code = "da", Name = "Danish" },
            new Language { Code = "nl", Name = "Dutch" },
            new Language { Code = "en", Name = "English" },
            new Language { Code = "eo", Name = "Esperanto" },
            new Language { Code = "et", Name = "Estonian" },
            new Language { Code = "fi", Name = "Finnish" },
            new Language { Code = "fr", Name = "French" },
            new Language { Code = "gl", Name = "Galician" },
            new Language { Code = "ka", Name = "Georgian" },
            new Language { Code = "de", Name = "German" },
            new Language { Code = "el", Name = "Greek" },
            new Language { Code = "gu", Name = "Gujarati" },
            new Language { Code = "ht", Name = "Haitian Creole" },
            new Language { Code = "ha", Name = "Hausa" },
            new Language { Code = "he", Name = "Hebrew" },
            new Language { Code = "hi", Name = "Hindi" },
            new Language { Code = "hu", Name = "Hungarian" },
            new Language { Code = "is", Name = "Icelandic" },
            new Language { Code = "id", Name = "Indonesian" },
            new Language { Code = "ga", Name = "Irish" },
            new Language { Code = "it", Name = "Italian" },
            new Language { Code = "ja", Name = "Japanese" },
            new Language { Code = "jv", Name = "Javanese" },
            new Language { Code = "kn", Name = "Kannada" },
            new Language { Code = "kk", Name = "Kazakh" },
            new Language { Code = "km", Name = "Khmer" },
            new Language { Code = "ko", Name = "Korean" },
            new Language { Code = "ku", Name = "Kurdish" },
            new Language { Code = "ky", Name = "Kyrgyz" },
            new Language { Code = "lo", Name = "Lao" },
            new Language { Code = "lv", Name = "Latvian" },
            new Language { Code = "lt", Name = "Lithuanian" },
            new Language { Code = "lb", Name = "Luxembourgish" },
            new Language { Code = "mk", Name = "Macedonian" },
            new Language { Code = "mg", Name = "Malagasy" },
            new Language { Code = "ms", Name = "Malay" },
            new Language { Code = "ml", Name = "Malayalam" },
            new Language { Code = "mt", Name = "Maltese" },
            new Language { Code = "mi", Name = "Maori" },
            new Language { Code = "mr", Name = "Marathi" },
            new Language { Code = "mn", Name = "Mongolian" },
            new Language { Code = "ne", Name = "Nepali" },
            new Language { Code = "no", Name = "Norwegian" },
            new Language { Code = "or", Name = "Oriya" },
            new Language { Code = "ps", Name = "Pashto" },
            new Language { Code = "fa", Name = "Persian" },
            new Language { Code = "pl", Name = "Polish" },
            new Language { Code = "pt", Name = "Portuguese" },
            new Language { Code = "pa", Name = "Punjabi" },
            new Language { Code = "ro", Name = "Romanian" },
            new Language { Code = "ru", Name = "Russian" },
            new Language { Code = "sm", Name = "Samoan" },
            new Language { Code = "gd", Name = "Scottish Gaelic" },
            new Language { Code = "sr", Name = "Serbian" },
            new Language { Code = "st", Name = "Sesotho" },
            new Language { Code = "sn", Name = "Shona" },
            new Language { Code = "sd", Name = "Sindhi" },
            new Language { Code = "si", Name = "Sinhala" },
            new Language { Code = "sk", Name = "Slovak" },
            new Language { Code = "sl", Name = "Slovenian" },
            new Language { Code = "so", Name = "Somali" },
            new Language { Code = "es", Name = "Spanish" },
            new Language { Code = "su", Name = "Sundanese" },
            new Language { Code = "sw", Name = "Swahili" },
            new Language { Code = "sv", Name = "Swedish" },
            new Language { Code = "tl", Name = "Tagalog" },
            new Language { Code = "tg", Name = "Tajik" },
            new Language { Code = "ta", Name = "Tamil" },
            new Language { Code = "tt", Name = "Tatar" },
            new Language { Code = "te", Name = "Telugu" },
            new Language { Code = "th", Name = "Thai" },
            new Language { Code = "tr", Name = "Turkish" },
            new Language { Code = "tk", Name = "Turkmen" },
            new Language { Code = "uk", Name = "Ukrainian" },
            new Language { Code = "ur", Name = "Urdu" },
            new Language { Code = "ug", Name = "Uyghur" },
            new Language { Code = "uz", Name = "Uzbek" },
            new Language { Code = "vi", Name = "Vietnamese" },
            new Language { Code = "cy", Name = "Welsh" },
            new Language { Code = "xh", Name = "Xhosa" },
            new Language { Code = "yi", Name = "Yiddish" },
            new Language { Code = "yo", Name = "Yoruba" },
            new Language { Code = "zu", Name = "Zulu" }
        ];
    }
}